<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/styles.css">
    <title>MEMENTO</title>
</head>
<body>
    <header>
        <ul class="navbar">
            <li><a href="#" class="navlogo">MEMENTO</a></li>
            <li><a href="#" class="navlogo">Mon Compte</a></li>
        </ul>
    </header>
    <main>
        <?php require './controllers/' . $route . '_controller.php'; ?>
    </main>
</body>
</html>