<div class="connex">
    <h1>Connexion</h1>
    <form action="./controllers/login_controller.php" method="post">
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required autofocus>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password" required>
        <input type="submit" value="Se connecter / S'enregistrer">
    </form>
</div>